-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Hewlett Packard HP E231 3CQ4281BC1",
  mode = "1920x1080@60.00",
  position = "0x-1080",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Samsung Display Corp. 0x416D",
  mode = "2880x1800@60.00",
  position = "0x0",
  scale = 1.5,
  vrr = 1,
  cm = "auto",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Samsung Display Corp. 0x416D", default = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Samsung Display Corp. 0x416D" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Samsung Display Corp. 0x416D" })
