# === Video ===
profile=gpu-hq
gpu-api=vulkan
hwdec=auto-safe

# === OSD / Font ===
osc=no
osd-font='CaskaydiaMono Nerd Font Propo'
osd-font-size=13
osd-color='#cdd6f4'
osd-border-color='#1e1e2e'
osd-border-size=1.5
osd-shadow-color='#11111b'
osd-shadow-offset=1

# === Window ===
border=no
keep-open=yes
autofit=80%x80%

# === Subtitles ===
sub-font='Caskaydia Mono Nerd Font Propo'
sub-font-size=38
sub-color='#cdd6f4'
sub-border-color='#1e1e2e'
sub-border-size=2
sub-shadow-color='#11111b'
sub-shadow-offset=1

save-position-on-quit=yes
write-filename-in-watch-later-config=yes
