background {
    monitor =
    path = /home/rivindu02/Pictures/Wallpapers/wallhaven-w56m1r.jpg
    blur_passes = 1
    blur_size = 4
    brightness = 0.6
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(74c7ec)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    font_family = CaskaydiaMono Nerd Font Mono
    placeholder_text = Password...
    fade_on_empty = true
    rounding = 8
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(cdd6f4ff)
    font_size = 64
    font_family = CaskaydiaMono Nerd Font Mono
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(74c7ecff)
    font_size = 20
    font_family = CaskaydiaMono Nerd Font Mono
    position = 0, 120
    halign = center
    valign = center
}
