-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = true,
    },
    decoration = {
        dim_around = 0.25,
        dim_inactive = true,
        dim_special = 0.15,
        dim_strength = 0.2,
        rounding_power = 2.0,
        shadow = {
            enabled = false,
        },
    },
    general = {
        allow_tearing = false,
        border_size = 2,
        col = {
            active_border = {
                colors = {"rgba(33ccffee)", "rgba(00ff99ee)", "rgba(e01b24ff)"},
                angle = 45,
            },
        },
        gaps_in = 4,
        gaps_out = 6,
        layout = "dwindle",
    },
    misc = {
        animate_manual_resizes = false,
        disable_hyprland_logo = true,
        vrr = 1,
    },
})

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = false,
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "2880x1800@120.00Hz",
    position = "4900x1090",
    scale = 1.5,
    cm = "srgb",
})
