background {
    monitor =
    path = /home/rivindu02/Pictures/Wallpapers/wallhaven-6l5mww.png
    blur_passes = 2
    blur_size = 6
    brightness = 0.5
}

input-field {
    monitor =
    size = 420, 65
    outline_thickness = 3
    outer_color = rgb(74c7ec)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    font_family = CaskaydiaMono Nerd Font Mono
    placeholder_text = Password...
    fade_on_empty = true
    rounding = 12

    position = 0, -180
    halign = center
    valign = center
}

# 🕒 Time (main focus)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(cdd6f4ff)
    font_size = 110
    font_family = CaskaydiaMono Nerd Font Mono

    position = 0, 260
    halign = center
    valign = center
}

# 📅 Date (secondary)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(74c7ecff)
    font_size = 28
    font_family = CaskaydiaMono Nerd Font Mono

    position = 0, 160
    halign = center
    valign = center
}
