-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    animations = {
        enabled = true,
    },
    cursor = {
        enable_hyprcursor = true,
    },
    decoration = {
        blur = {
            enabled = true,
        },
        dim_around = 0.25,
        dim_inactive = true,
        dim_special = 0.15,
        dim_strength = 0.2,
        rounding = 2,
        shadow = {
            enabled = true,
        },
    },
    general = {
        allow_tearing = false,
        border_size = 2,
        col = {
            active_border = {
                colors = {"rgba(33ccffee)", "rgba(00ff99ee)", "rgba(e01b24ff)"},
                angle = 45,
            },
        },
        gaps_in = 4,
        gaps_out = 6,
        layout = "dwindle",
    },
    gestures = {
        workspace_swipe_forever = false,
        workspace_swipe_touch = true,
    },
    misc = {
        animate_manual_resizes = false,
        disable_hyprland_logo = true,
        vrr = 1,
    },
})

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = false,
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "2880x1800@120.00Hz",
    position = "0x0",
    scale = 1.5,
    cm = "srgb",
})
