-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = true,
    },
    decoration = {
        dim_around = 0.25,
        dim_inactive = true,
        dim_special = 0.15,
        dim_strength = 0.2,
        rounding_power = 2.0,
        shadow = {
            enabled = false,
        },
    },
    general = {
        allow_tearing = false,
        border_size = 2,
        gaps_in = 4,
        gaps_out = 6,
    },
    misc = {
        animate_manual_resizes = false,
        disable_hyprland_logo = true,
    },
})

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = false,
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "2880x1800@120.00Hz",
    position = "4951x1086",
    scale = 1.5,
    cm = "srgb",
})
