-- Generated by hyprmoncfg
hl.workspace_rule({ workspace = "1", monitor = "desc:Samsung Display Corp. 0x416D", default = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Samsung Display Corp. 0x416D" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Samsung Display Corp. 0x416D" })
hl.workspace_rule({ workspace = "4", monitor = "desc:ViewSonic Corporation VA240A Series XZ0252600635", default = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:ViewSonic Corporation VA240A Series XZ0252600635" })
