[[mgr.prepend_keymap]]
on = ["R"]
run = "rename --empty=all"
desc = "Bulk rename"

[[mgr.prepend_keymap]]
desc = "Start bunny.yazi"
on = "b"
run = "plugin bunny"

# Optionally, add another keymap to immediately fuzzy search bookmarks
[[mgr.prepend_keymap]]
desc = "Start bunny.yazi fuzzy search"
on = "'"
run = "plugin bunny fuzzy"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"
desc = "Mount manager"

[[manager.prepend_keymap]]
on = "y"
run = [ 'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list' , "yank" ]

[[mgr.prepend_keymap]]
on = "Y"
run = 'shell -- wl-copy -t "$(file --mime-type -b "$1")" < "$1"'
desc = "Copy file content to clipboard"
